image: "rust:latest"

stages:
    - lint
    - test

lint:fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script:
        - cargo fmt --all -- --check

lint:clippy:
    stage: lint
    before_script:
        - rustup component add clippy
    script: cargo clippy -- --deny warnings
    allow_failure: true

.test: &test
    stage: test
    before_script:
        - apt update
        - apt install sudo postgresql postgresql-server-dev-11 valgrind -y
        - sudo -u postgres pg_ctlcluster 11 main start
        - sudo -u postgres psql --command "create role root WITH LOGIN ENCRYPTED PASSWORD '1234';";
        - sudo -u postgres psql --command "create database root with owner root;";
        - export PQ_DSN='host=localhost password=1234'

test:debug:
    <<: *test
    script: cargo test

test:release:
    <<: *test
    script: cargo test --release

test:valgrind:
    <<: *test
    script:
      - cargo test --no-run
      - valgrind --leak-check=full --error-exitcode=1 $(find target/debug/deps -executable -type f)
